---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bwyaz.
--- DateTime: 11/28/2018 3:40 PM
---


local ButtonObj = setmetatable({}, {__index = CreateFrame("CheckButton")}) --this is the metatable for our button object
Neuron.ButtonObj = ButtonObj

local SKIN = LibStub("Masque", true)

local BTNIndex, SKINIndex = Neuron.BTNIndex, Neuron.SKINIndex


local keyDefaults = {
	[1] = { hotKeys = ":1:", hotKeyText = ":1:" },
	[2] = { hotKeys = ":2:", hotKeyText = ":2:" },
	[3] = { hotKeys = ":3:", hotKeyText = ":3:" },
	[4] = { hotKeys = ":4:", hotKeyText = ":4:" },
	[5] = { hotKeys = ":5:", hotKeyText = ":5:" },
	[6] = { hotKeys = ":6:", hotKeyText = ":6:" },
	[7] = { hotKeys = ":7:", hotKeyText = ":7:" },
	[8] = { hotKeys = ":8:", hotKeyText = ":8:" },
	[9] = { hotKeys = ":9:", hotKeyText = ":9:" },
	[10] = { hotKeys = ":0:", hotKeyText = ":0:" },
	[11] = { hotKeys = ":-:", hotKeyText = ":-:" },
	[12] = { hotKeys = ":=:", hotKeyText = ":=:" },
}




---Button Constructor
---@param name string @ Name given to the new button frame
---@param frameType string @ Type of frame to create
---@param frameTemplate @ Template used for our new frame
---@param objMetaTable @ Metatable object to be assigned as the template for our new button
function ButtonObj:new(name, frameType, frameTemplate, objMetaTable)

	local object = CreateFrame(frameType, name, UIParent, frameTemplate)

	setmetatable(object, objMetaTable)

	return object
end



-------------------------------------------------
-----Base Methods that all buttons have----------
---These will often be overwritten per bar type--
-------------------------------------------------
function ButtonObj:SetData(bar)
	if (bar) then

		self.bar = bar

		self.barLock = bar.data.barLock
		self.barLockAlt = bar.data.barLockAlt
		self.barLockCtrl = bar.data.barLockCtrl
		self.barLockShift = bar.data.barLockShift

		self.tooltips = bar.data.tooltips
		self.tooltipsEnhanced = bar.data.tooltipsEnhanced
		self.tooltipsCombat = bar.data.tooltipsCombat

		self.spellGlow = bar.data.spellGlow
		self.spellGlowDef = bar.data.spellGlowDef
		self.spellGlowAlt = bar.data.spellGlowAlt

		self.bindText = bar.data.bindText
		self.macroText = bar.data.macroText
		self.countText = bar.data.countText

		self.cdText = bar.data.cdText

		if (bar.data.cdAlpha) then
			self.cdAlpha = 0.2
		else
			self.cdAlpha = 1
		end

		self.auraText = bar.data.auraText
		self.auraInd = bar.data.auraInd

		self.rangeInd = bar.data.rangeInd

		self.upClicks = bar.data.upClicks
		self.downClicks = bar.data.downClicks

		self.showGrid = bar.data.showGrid
		self.multiSpec = bar.data.multiSpec

		self.bindColor = bar.data.bindColor
		self.macroColor = bar.data.macroColor
		self.countColor = bar.data.countColor

		self.macroname:SetText(self.data.macro_Name) --custom macro's weren't showing the name

		if (not self.cdcolor1) then
			self.cdcolor1 = { (";"):split(bar.data.cdcolor1) }
		else
			self.cdcolor1[1], self.cdcolor1[2], self.cdcolor1[3], self.cdcolor1[4] = (";"):split(bar.data.cdcolor1)
		end

		if (not self.cdcolor2) then
			self.cdcolor2 = { (";"):split(bar.data.cdcolor2) }
		else
			self.cdcolor2[1], self.cdcolor2[2], self.cdcolor2[3], self.cdcolor2[4] = (";"):split(bar.data.cdcolor2)
		end

		if (not self.auracolor1) then
			self.auracolor1 = { (";"):split(bar.data.auracolor1) }
		else
			self.auracolor1[1], self.auracolor1[2], self.auracolor1[3], self.auracolor1[4] = (";"):split(bar.data.auracolor1)
		end

		if (not self.auracolor2) then
			self.auracolor2 = { (";"):split(bar.data.auracolor2) }
		else
			self.auracolor2[1], self.auracolor2[2], self.auracolor2[3], self.auracolor2[4] = (";"):split(bar.data.auracolor2)
		end

		if (not self.buffcolor) then
			self.buffcolor = { (";"):split(bar.data.buffcolor) }
		else
			self.buffcolor[1], self.buffcolor[2], self.buffcolor[3], self.buffcolor[4] = (";"):split(bar.data.buffcolor)
		end

		if (not self.debuffcolor) then
			self.debuffcolor = { (";"):split(bar.data.debuffcolor) }
		else
			self.debuffcolor[1], self.debuffcolor[2], self.debuffcolor[3], self.debuffcolor[4] = (";"):split(bar.data.debuffcolor)
		end

		if (not self.rangecolor) then
			self.rangecolor = { (";"):split(bar.data.rangecolor) }
		else
			self.rangecolor[1], self.rangecolor[2], self.rangecolor[3], self.rangecolor[4] = (";"):split(bar.data.rangecolor)
		end

		self:SetFrameStrata(bar.data.objectStrata)

		self:SetScale(bar.data.scale)
	end

	if (self.bindText) then
		self.hotkey:Show()
		if (self.bindColor) then
			self.hotkey:SetTextColor((";"):split(self.bindColor))
		end
	else
		self.hotkey:Hide()
	end

	if (self.macroText) then
		self.macroname:Show()
		if (self.macroColor) then
			self.macroname:SetTextColor((";"):split(self.macroColor))
		end
	else
		self.macroname:Hide()
	end

	if (self.countText) then
		self.count:Show()
		if (self.countColor) then
			self.count:SetTextColor((";"):split(self.countColor))
		end
	else
		self.count:Hide()
	end

	local down, up = "", ""

	if (self.upClicks) then up = up.."AnyUp" end
	if (self.downClicks) then down = down.."AnyDown" end

	self:RegisterForClicks(down, up)
	self:RegisterForDrag("LeftButton", "RightButton")
	self:RegisterEvent("PLAYER_ENTERING_WORLD")

	if (not self.equipcolor) then
		self.equipcolor = { 0.1, 1, 0.1, 1 }
	else
		self.equipcolor[1], self.equipcolor[2], self.equipcolor[3], self.equipcolor[4] = 0.1, 1, 0.1, 1
	end

	if (not self.manacolor) then
		self.manacolor = { 0.5, 0.5, 1.0, 1 }
	else
		self.manacolor[1], self.manacolor[2], self.manacolor[3], self.manacolor[4] = 0.5, 0.5, 1.0, 1
	end

	self:SetFrameLevel(4)
	self.iconframe:SetFrameLevel(2)
	self.iconframecooldown:SetFrameLevel(3)
	self.iconframeaurawatch:SetFrameLevel(3)

	self:GetSkinned(self)

	Neuron.NeuronButton:MACRO_UpdateTimers(self)
end



function ButtonObj:LoadData(spec, state)

	local DB = Neuron.db.profile

	local id = self.id

	if (not DB.buttons[id]) then
		DB.buttons[id] = {}
	end

	self.DB = DB.buttons[id]

	self.config = self.DB.config
	self.keys = self.DB.keys
	self.statedata = self.DB[spec] --all of the states for a given spec
	self.data = self.statedata[state] --loads a single state of a single spec into button.data

	Neuron.NeuronButton:BuildStateData(self)
end




function ButtonObj:SetObjectVisibility(button, show)

	if not InCombatLockdown() then
		button:SetAttribute("showGrid", button.showGrid) --this is important because in our state switching code, we can't querry button.showGrid directly
		button:SetAttribute("isshown", show)
	end

	if (show or button.showGrid) then
		button:Show()
	elseif not Neuron.NeuronButton:MACRO_HasAction(button) and (not Neuron.ButtonEditMode or not Neuron.BarEditMode or not Neuron.BindingMode) then
		button:Hide()
	end
end



function ButtonObj:SetAux(button)
	button:SetSkinned(button)
	Neuron.NeuronFlyouts:UpdateFlyout(button, true)
end


function ButtonObj:LoadAux(button)

	if Neuron.NeuronGUI then
		Neuron.NeuronGUI:ObjEditor_CreateEditFrame(button, button.objTIndex)
	end
	Neuron.NeuronBinder:CreateBindFrame(button, button.objTIndex)

end


function ButtonObj:SetDefaults(button, config, keys)
	if (config) then
		for k,v in pairs(config) do
			button.config[k] = v
		end
	end

	if (keys) then
		for k,v in pairs(keys) do
			button.keys[k] = v
		end
	end
end


function ButtonObj:GetDefaults(button)
	return nil, keyDefaults[button.id]
end




function ButtonObj:SetType(button, save, kill, init)
	local state = button:GetParent():GetAttribute("activestate")

	Neuron.NeuronButton:Reset(button)

	if (kill) then

		button:SetScript("OnEvent", function() end)
		button:SetScript("OnUpdate", function() end)
		button:SetScript("OnAttributeChanged", function() end)

	else
		SecureHandler_OnLoad(button)

		button:RegisterEvent("ITEM_LOCK_CHANGED")
		button:RegisterEvent("ACTIONBAR_SHOWGRID")
		button:RegisterEvent("ACTIONBAR_HIDEGRID")

		button:RegisterEvent("ACTIVE_TALENT_GROUP_CHANGED")
		button:RegisterEvent("UPDATE_MACROS")
		button:RegisterEvent("PLAYER_EQUIPMENT_CHANGED")
		button:RegisterEvent("EQUIPMENT_SETS_CHANGED")

		Neuron.NeuronButton:MACRO_UpdateParse(button)

		button:SetAttribute("type", "macro")
		button:SetAttribute("*macrotext*", button.macroparse)

		button:SetScript("OnEvent", function(self, event, ...) Neuron.NeuronButton:MACRO_OnEvent(self, event, ...) end)
		button:SetScript("PreClick", function(self, mousebutton) Neuron.NeuronButton:MACRO_PreClick(self, mousebutton) end)
		button:SetScript("PostClick", function(self, mousebutton) Neuron.NeuronButton:MACRO_PostClick(self, mousebutton) end)
		button:SetScript("OnReceiveDrag", function(self, preclick) Neuron.NeuronButton:MACRO_OnReceiveDrag(self, preclick) end)
		button:SetScript("OnDragStart", function(self, mousebutton) Neuron.NeuronButton:MACRO_OnDragStart(self, mousebutton) end)
		button:SetScript("OnDragStop", function(self) Neuron.NeuronButton:MACRO_OnDragStop(self) end)
		button:SetScript("OnUpdate", function(self, elapsed) Neuron.NeuronButton:MACRO_OnUpdate(self, elapsed) end)--this function uses A LOT of CPU resources
		button:SetScript("OnShow", function(self, ...) Neuron.NeuronButton:MACRO_OnShow(self, ...) end)
		button:SetScript("OnHide", function(self, ...) Neuron.NeuronButton:MACRO_OnHide(self, ...) end)
		button:SetScript("OnAttributeChanged", function(self, name, value) Neuron.NeuronButton:MACRO_OnAttributeChanged(self, name, value) end)

		button:HookScript("OnEnter", function(self, ...) Neuron.NeuronButton:MACRO_OnEnter(self, ...) end)
		button:HookScript("OnLeave", function(self, ...) Neuron.NeuronButton:MACRO_OnLeave(self, ...) end)

		button:WrapScript(button, "OnShow", [[
						for i=1,select('#',(":"):split(self:GetAttribute("hotkeys"))) do
							self:SetBindingClick(self:GetAttribute("hotkeypri"), select(i,(":"):split(self:GetAttribute("hotkeys"))), self:GetName())
						end
						]])

		button:WrapScript(button, "OnHide", [[
						if (not self:GetParent():GetAttribute("concealed")) then
							for key in gmatch(self:GetAttribute("hotkeys"), "[^:]+") do
								self:ClearBinding(key)
							end
						end
						]])

		--new action ID's for vehicle 133-138
		--new action ID's for possess 133-138
		--new action ID's for override 157-162

		button:SetAttribute("overrideID_Offset", 156)
		button:SetAttribute("vehicleID_Offset", 132)

		button:SetAttribute("_childupdate", [=[

				if (message) then

					local msg = (":"):split(message)

					if (msg:find("vehicle")) then

						if (not self:GetAttribute(msg.."-actionID")) then

							self:SetAttribute("type", "action")
							self:SetAttribute("*action*", self:GetAttribute("barPos")+self:GetAttribute("vehicleID_Offset"))

						end

						self:SetAttribute("SpecialAction", "vehicle")
						self:SetAttribute("HasActionID", true)
						self:Show()

					elseif (msg:find("possess")) then
						if (not self:GetAttribute(msg.."-actionID")) then

							self:SetAttribute("type", "action")
							self:SetAttribute("*action*", self:GetAttribute("barPos")+self:GetAttribute("vehicleID_Offset"))

						end

						self:SetAttribute("SpecialAction", "possess")
						self:SetAttribute("HasActionID", true)
						self:Show()

					elseif (msg:find("override")) then
						if (not self:GetAttribute(msg.."-actionID")) then

							self:SetAttribute("type", "action")
							self:SetAttribute("*action*", self:GetAttribute("barPos")+self:GetAttribute("overrideID_Offset"))
							self:SetAttribute("HasActionID", true)

						end

						self:SetAttribute("SpecialAction", "override")

						self:SetAttribute("HasActionID", true)

						self:Show()

					else
						if (not self:GetAttribute(msg.."-actionID")) then

							self:SetAttribute("type", "macro")
							self:SetAttribute("*macrotext*", self:GetAttribute(msg.."-macro_Text"))

							if (self:GetAttribute("*macrotext*") and #self:GetAttribute("*macrotext*") > 0) or self:GetAttribute("isshown") then
								self:Show()
							elseif (not self:GetAttribute("showGrid")) then
								self:Hide()
							end

							self:SetAttribute("HasActionID", false)
						else
							self:SetAttribute("HasActionID", true)
						end

						self:SetAttribute("SpecialAction", nil)
					end

					self:SetAttribute("useparent-unit", nil)
					self:SetAttribute("activestate", msg)

				end

			]=])

		if (not init) then
			Neuron.NeuronButton:MACRO_UpdateAll(button, true)
		end

		Neuron.NeuronButton:MACRO_OnShow(button)

	end

end


function ButtonObj:SetSkinned(button, flyout)
	if (SKIN) then
		local bar = button.bar

		if (bar) then
			local btnData = {
				Normal = button.normaltexture,
				Icon = button.iconframeicon,
				Cooldown = button.iconframecooldown,
				HotKey = button.hotkey,
				Count = button.count,
				Name = button.name,
				Border = button.border,
				AutoCast = false,
			}

			if (flyout) then
				SKIN:Group("Neuron", button.anchor.bar.data.name):AddButton(button, btnData)
			else
				SKIN:Group("Neuron", bar.data.name):AddButton(button, btnData)
			end

			button.skinned = true

			SKINIndex[button] = true
		end
	end
end


function ButtonObj:GetSkinned(button)
	if (button.__MSQ_NormalTexture) then
		local Skin = button.__MSQ_NormalSkin

		if (Skin) then
			button.hasAction = Skin.Texture or false
			button.noAction = Skin.EmptyTexture or false

			if (button.__MSQ_Shape) then
				button.shape = button.__MSQ_Shape:lower()
			else
				button.shape = "square"
			end
		else
			button.hasAction = false
			button.noAction = false
			button.shape = "square"
		end

		button.shine.shape = button.shape

		return true
	else
		button.hasAction = "Interface\\Buttons\\UI-Quickslot2"
		button.noAction = "Interface\\Buttons\\UI-Quickslot"

		return false
	end
end

------------------------------------------------------------
--------------General Button Methods--------------------------
------------------------------------------------------------
